language: bash
dist: focal

before_install:
  - gem install bashcov simplecov 'simplecov-cobertura'
  - sudo apt-get install parallel

script:
  - tests/libs/bats/bin/bats tests/integration_offline.bats

after_success:
  - bashcov tests/libs/bats/bin/bats tests/integration_offline.bats
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov

notifications:
  email: false
