language: bash
dist: noble

before_install:
  - sudo apt-get install parallel
  - gem install bashcov:3.1.0 simplecov:0.21.2 codecov:0.6.0  # Specific versions compatible with simplecov that works on codecov, bashcov:3.2.0 was incompatible
  - echo -e "require 'codecov'\nrequire 'simplecov'\nSimpleCov.formatter = Codecov::SimpleCov::Formatter" > .simplecov # to generate .json codecov coverage report
   
script:
  - shellcheck genome_updater.sh
  - bashcov --skip-uncovered tests/libs/bats/bin/bats tests/integration_offline.bats

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -f coverage/codecov-result.json -Z

notifications:
  email: false
