language: bash
dist: focal

before_install:
  - bundle update --bundler && bundle install
  - gem install bashcov simplecov
  - sudo apt-get install parallel

script:
  - bashcov tests/libs/bats/bin/bats tests/integration_offline.bats

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -f coverage/.resultset.json -Z

notifications:
  email: false
