language: bash
dist: jammy

before_install:
  - gem install bashcov codecov
  - sudo apt-get install parallel
  - echo -e "require 'codecov'\nrequire 'simplecov'\nSimpleCov.formatter = Codecov::SimpleCov::Formatter" > .simplecov

script:
  - bashcov tests/libs/bats/bin/bats tests/integration_offline.bats

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -f coverage/codecov-result.json -Z

notifications:
  email: false
