language: bash
dist: noble

before_install:
  - sudo apt-get install parallel
  - gem install bashcov codecov
  - echo -e "SimpleCov.start do\n  add_filter 'tests/'\nend" > .simplecov

script:
  - shellcheck genome_updater.sh
  - bashcov --skip-uncovered tests/libs/bats/bin/bats tests/integration_offline.bats

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -f coverage/.result.json -Z

notifications:
  email: false
