language: bash
dist: focal

before_install:
  - gem install bashcov simplecov 'simplecov-cobertura'
  - sudo apt-get install parallel

script:
  - bashcov tests/libs/bats/bin/bats tests/integration_offline.bats

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - cat coverage/.resultset.json
  - ./codecov -f coverage/.resultset.json

notifications:
  email: false
